### ISSUE TITLE
Bug with header description when generated from the filename

### ISSUE THREAD

**Issue by MrYannKee** [Hirevo/epitech-c-cpp-headers#5]
## Description
When leaving the description field blank, if the filename contains the same characters as the file extension, it cuts the filename in an unexpected way.

### Example 1
File name: `particle_manager.c`
```
/*
** EPITECH PROJECT, 2018
** project
** File description:
** partile_manager.
*/
```
Expected result:
```
/*
** EPITECH PROJECT, 2018
** project
** File description:
** particle_manager
*/
```
### Example 2
File name: `this_is_a_test.h`
```
/*
** EPITECH PROJECT, 2018
** project
** File description:
** tis_is_a_test.
*/
```
Expected result:
```
/*
** EPITECH PROJECT, 2018
** project
** File description:
** this_is_a_test
*/
```
### Example 3
File name: `this_cpp_file.cpp`
```
/*
** EPITECH PROJECT, 2018
** project
** File description:
** this__file.cp
*/
```
Expected result:
```
/*
** EPITECH PROJECT, 2018
** project
** File description:
** this_cpp_file
*/
```

**Comment by MrYannKee** [comment]
I'm trying to fix the issue.

**Comment by Hirevo** [comment]
Hello,

Sorry for the delay, I've got quite a lot of things to do these past few weeks.
Thanks a lot for reporting the issue.
I see that you managed to fix it in PR #6.
This bug was introduced in the last update and you now use the same method than I used to generate the class names from the filename.
Thanks again for the bug report and I'll approve your PR.

Have a nice day.

**Comment by Hirevo** [comment]
The fix should be deployed to everyone along with better support for files without extensions.

**Comment by MrYannKee** [comment]
I forgot the check the fix for files without extensions. Thank you for fixing it.
